=== 5l1v3r1/smartcheck/src/main/resources/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Rules" type="rulesResource"/>
  <xs:complexType name="rulesResource" final="extension restriction">
    <xs:sequence>
      <xs:element name="Rule" type="ruleResource" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ruleResource" final="extension restriction">
    <xs:sequence>
      <xs:element name="Pattern" type="patternResource" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="patternResource" final="extension restriction">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="severity" type="xs:int" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== 5l1v3r1/smartcheck/rules/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./rules.xsd">
    <Rule id="SOLIDITY_TX_ORIGIN">
     <Pattern id="5508c4" severity="2">//expression[expression[1]/primaryExpression/text()[1]="tx"][text()[1]=".origin"]</Pattern> 
    </Rule>
    <Rule id="SOLIDITY_UNCHECKED_SEND">
      <Pattern id="19e999" severity="3">
        //simpleStatement[expressionStatement/expression/functionCall[matches(text()[1],"^.+\.send\($")]]
      </Pattern>
    </Rule>
    <Rule id="SOLIDITY_CALL_VALUE">
      <Pattern id="f68a3a" severity="3">
        //functionCall[matches(text()[1],"^.+\.call\.value\($")]
      </Pattern>
    </Rule>
    <Rule id="SOLIDITY_BALANCE_EQUALITY">
      <Pattern id="7a3b44" severity="2">
        //expression[expression[expression/primaryExpression[text()[1]="this"]][text()[1]=".balance"]][text()[1]="=="]
      </Pattern>
    </Rule>
    <Rule id="SOLIDITY_STYLE_GUIDE_VIOLATION">
      <Pattern id="67c4ca" severity="1">
        //eventDefinition[matches(text()[1],"^event[a-z].*$")]
      </Pattern>
      <Pattern id="4fc198" severity="1">
        //functionDefinition[matches(text()[1],"^function[A-Z].*$")]
      </Pattern>
    </Rule>
</Rules>

=== 5l1v3r1/smartcheck/src/main/resources/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./rules.xsd">
    <VersionDefinition>//pragmaDirective[pragmaName='solidity']/pragmaValue/version/versionConstraint/text()</VersionDefinition>
    <!--<Rule id="BAD_PRAGMA_EXAMPLE">
        <VersionPattern id="pragma" severity="1" max="0.4.10"/>
    </Rule>-->
    <!--<Rule id="SOLIDITY_EXAMPLE_RULE">
        <Pattern id="ca5323" severity="1">//contractDefinition</Pattern>
        <Pattern id="e0827f" severity="2" max="0.4.6">//functionDefinition</Pattern>
    </Rule>-->
    <Rule id="SOLIDITY_TX_ORIGIN">
        <Pattern id="5508c4" severity="2">//expression
            [expression/primaryExpression[matches(text()[1],"tx")]]
            [matches(text()[1],".")]
            [matches(text()[1],"origin")]</Pattern>
    </Rule>
    <Rule id="SOLIDITY_UNCHECKED_SEND">
        <Pattern id="19e999" severity="3">
            //simpleStatement[expressionStatement/expression/functionCall[matches(text()[1],"^.+\.send\($")]]
        </Pattern>
    </Rule>
    <Rule id="SOLIDITY_CALL_VALUE">
        <Pattern id="f68a3a" severity="3">
            //functionCall[matches(text()[1],"^.+\.call\.value\($")]
        </Pattern>
    </Rule>
    <Rule id="SOLIDITY_BALANCE_EQUALITY">
        <Pattern id="7a3b44" severity="2">
            //expression[expression[expression/primaryExpression[text()[1]="this"]][text()[1]=".balance"]][text()[1]="=="]
        </Pattern>
    </Rule>
    <Rule id="SOLIDITY_STYLE_GUIDE_VIOLATION">
        <Pattern id="67c4ca" severity="1">
            //eventDefinition[matches(text()[1],"^event[a-z].*$")]
        </Pattern>
        <Pattern id="4fc198" severity="1">
            //functionDefinition[matches(text()[1],"^function[A-Z].*$")]
        </Pattern>
    </Rule>
    <Rule id="SOLIDITY_VAR_ZERO">
        <Pattern id="8a1549" severity="2">
            //forStatement/simpleStatement/variableDeclarationStatement[variableDeclaration//elementaryTypeName[matches(text()[1],"var")]][expression//numberLiteral[matches(text()[1],"0")]]
        </Pattern>
    </Rule>
    <!--<Rule id="SOLIDITY_CHECKS_EFFECTS_INTERACTIONS_REENTRANCY">
        <Pattern id="8a1600" severity="2">
            //block/following-sibling::statement[//functionCall]/simpleStatement//primaryExpression
        </Pattern>
    </Rule>-->
    <Rule id="SOLIDITY_GAS_LIMIT_AND_LOOPS">
        <Pattern id="8a1809" severity="2">
            //forStatement/expression[1]/expression[2]/expression/primaryExpression
        </Pattern>
    </Rule>
   <!-- <Rule id="SOLIDITY_ TIMESTAMP_DEPENDENCE">
        <Pattern id="8a1044" severity="2">
            //expression/primaryExpression[matches(text()[1],"now")]
        </Pattern>
    </Rule>-->

</Rules>
